In [2]:
name = input("what's your name ？")
sum = 100 +100
print('hello,%s'%name)
print('sum =%d'%sum)

what's your name ？wew
hello,wew
sum =200


In [9]:
#条件判断
score = input("plase input score:")
score = int(score)
if score >= 90:
    print('Excellent')
else:
    if score  <  60:
        print('Fail')
    else:
        print('Good Job')

plase input score:56
Fail


In [15]:
sum = 0
for number in range(11):
    sum = sum + number
print(sum)

#while 循环
sum = 0
number = 1
while number < 11:
    sum = sum + number
    number += 1
print(sum)

55
55


In [21]:
lists = ['zhangfei',"guanyu",'liubei']
lists.append("dainwei")
print(lists)
print(len(lists))
lists.insert(1,"lvbu")
lists.pop()
lists.pop(0)
print(lists)

['zhangfei', 'guanyu', 'liubei', 'dainwei']
4
['lvbu', 'guanyu', 'liubei']


In [24]:
tuples = ('zhangfei',65)
print(type(tuples))

<class 'tuple'>


In [28]:
tuples = ('zhangfei',65)
print(type(tuples))
#print(tuples[({'zhangfei':65,'guanyu':99})
print(tuple({'zhangfei':65, 'guanyu':99}))

<class 'tuple'>
('zhangfei', 'guanyu')


In [30]:
temp_list = [123,'zhangfei','guanyu','liubei']
temp_tuple = tuple(temp_list)
print(temp_tuple)

(123, 'zhangfei', 'guanyu', 'liubei')


In [31]:
score = {'guanyu':96,'zhangfei':95}
score['zhaoyun'] = 98
print(score)

{'guanyu': 96, 'zhangfei': 95, 'zhaoyun': 98}


In [34]:
score.pop('guanyu')
print(score)

{'zhangfei': 95, 'zhaoyun': 98}


In [36]:
print('zhangfei' in score)

True


In [37]:
print(score.get('zhangfei'))

95


In [38]:
print(score['zhangfei'])

95


In [3]:
import numpy as np
#ndarray使用
def work1():
    a = np.array([1,2,3])
    b = np.array([[1,2,3],[4,5,6],[7,8,9],[1,2,3]])
    b[1,1] = 10
    print(a.shape)
    print(b.shape)
    print(a.dtype)
    print(b)
work1()

(3,)
(4, 3)
int32
[[ 1  2  3]
 [ 4 10  6]
 [ 7  8  9]
 [ 1  2  3]]


In [13]:
import numpy as np
def work2():
    persontype = np.dtype({'names':['name','age','chinese','math','english'],\
                          'formats':['S32','i','i','i','f']})
    peoples = np.array([("zhangfei",32,75,100,90),("guanyu",24,85,96,88.5),\
                        ("zhaoyun",28,85,92,96.5),("huangzhong",29,65,85,100)],\
                       dtype = persontype)
    ages = peoples['age']
    chineses = peoples['chinese']
    englishs = peoples['english']
    maths = peoples['math']
    print(np.mean(ages))
    print(np.mean(chineses))
    print(np.mean(maths))
    print(np.mean(englishs))
work2()

28.25
77.5
93.25
93.75


In [25]:
import numpy as np
x1 = np.arange(1,11,2)
x2 = np.linspace(1,9,5)
print('x1=',x1)
print('x2=',x2)
print(np.add(x1,x2))
print(np.subtract(x1,x2))
print(np.multiply(x1,x2))
print(np.divide(x1,x2))
print(np.power(x1,x2))
print(np.remainder(x1,x2))

x1= [1 3 5 7 9]
x2= [1. 3. 5. 7. 9.]
[ 2.  6. 10. 14. 18.]
[0. 0. 0. 0. 0.]
[ 1.  9. 25. 49. 81.]
[1. 1. 1. 1. 1.]
[1.00000000e+00 2.70000000e+01 3.12500000e+03 8.23543000e+05
 3.87420489e+08]
[0. 0. 0. 0. 0.]


# numpy中统计函数的使用


In [27]:
import numpy as np
def work1():
    a = np.array([[1,2,3],[4,5,6],[7,8,9]])
    print(a)
    print('-'*20)
    print(np.min(a))
    print(np.min(a,0))#  每一列 最小值
    print(np.min(a,1))#每一行 最小值
    print(np.max(a))
    print(np.max(a,1))
    print(np.max(a,0))
work1()

[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------
1
[1 2 3]
[1 4 7]
9
[3 6 9]
[7 8 9]


In [39]:
import numpy as np
def work2():
    a = np.array([[1,2,3],[4,5,6],[7,8,9]])
    #a = np.array([1,2,3,4,5,6,7,8,9])
    print(np.percentile(a,50))
    print(np.percentile(a,50,axis = 0))
    print(np.percentile(a,50,axis = 1))
    
    
    
work2()

5.0
[4. 5. 6.]
[2. 5. 8.]


In [44]:
import numpy as np
def work3():
    a = np.array([[1,2,3],[4,5,6],[7,8,9]])
    #a = [1,2,3,4]
    print(np.median(a))
    print(np.median(a,axis=0))
    print(np.median(a,axis=1))
    print(np.mean(a))
    print(np.mean(a,axis=0))
    print(np.mean(a,axis=1))

    
work3()
    

5.0
[4. 5. 6.]
[2. 5. 8.]
5.0
[4. 5. 6.]
[2. 5. 8.]


In [46]:
import numpy as np
a = np.array([1,2,3,4])
weights = np.array([1,2,3,4])
print(np.average(a))
print(np.average(a,weights = weights))

2.5
3.0


In [47]:
import numpy 
a = numpy.array([1,2,3,4])
print(numpy.std(a))#标准差
print(numpy.var(a))#方差

1.118033988749895
1.25


In [50]:
import numpy as np
a = np.array([[4,3,2],[2,4,1]])
print(a)
print(np.sort(a))
print(np.sort(a,axis = None))
print(np.sort(a,axis = 0))
print(np.sort(a,axis = 1))

[[4 3 2]
 [2 4 1]]
[[2 3 4]
 [1 2 4]]
[1 2 2 3 4 4]
[[2 3 1]
 [4 4 2]]
[[2 3 4]
 [1 2 4]]


In [52]:
a = [4,3,2,2,4,1]
print(type(a))
a.sort()
print(a)
a.sort(reverse  = True)
print(a)

<class 'list'>
[1, 2, 2, 3, 4, 4]
[4, 4, 3, 2, 2, 1]
